# Generated by Django 2.2.2 on 2019-06-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cinemareview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('review', models.TextField(blank=True, max_length=1000, null=True, verbose_name='レビュー')),
                ('rate', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, verbose_name='レート')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='レビュー日時')),
            ],
        ),
    ]
